SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/top_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSystolic.v $(PWD)/verilog/systolicUnit.v

EXTRA_ARGS = --trace --trace-structs -Wno-TIMESCALEMOD

TOPLEVEL = mkSystolic
MODULE   := top

include $(shell cocotb-config --makefiles)/Makefile.sim
